version: "3.8"

services:
  # postgres:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - DATABASE_HOST=127.0.0.1
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=root

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - postgres

  mysqlDB:
    image: mysql:8.0.32
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
      - MYSQL_DATABASE=clientes

#  mysql-workbench:
#    image: lscr.io/linuxserver/mysql-workbench:latest
#    container_name: mysql-workbench
#    environment:
#      - PUID=0
#      - PGID=0
#      - TZ=Etc/UTC
#    volumes:
#      - /path/to/config:/config
#    ports:
#      - "3000:3000"
#    cap_add:
#      - IPC_LOCK
#    restart: unless-stopped
